schema_version = "1.0.0"

id = "just_simple_rig"
version = "1.0.0"
name = "Just Simple Rig"
tagline = "A simple and flexible Minecraft character rig"
maintainer = "Aspirata"
type = "add-on"

website = "https://aspirata.github.io/Just-Simple-Rig"

tags = ["Animation", "Rigging"]

blender_version_min = "4.2.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:MIT",
]

copyright = [
  "2025-2026 Aspirata",
]

[permissions]
files = "Import Rig"